import React, { AllHTMLAttributes } from "react";
import "{2}";
/* 
  Attention: This file is generated by "yarn icon", do not modify 
*/

export enum IconClass {
// {1}
}


interface Props extends AllHTMLAttributes<HTMLElement> {
  type: IconClass;
}

export default class Component extends React.PureComponent<Props> {
  static defaultProps = {
    symbol: false
  };

  render() {
    const { type, symbol, className = "", ...restProps } = this.props;
    return symbol ? (
      <svg
        className={`{3} ${className}`}
        style={{
          width: "1em",
          height: "1em",
          verticalAlign: "-0.15em",
          fill: "currentColor",
          overflow: "hidden"
        }}
        aria-hidden="true"
      >
        <use xlinkHref={`#${type}`}></use>
      </svg>
    ) : (
      <i className={`{3} ${type} ${className}`} {...restProps} />
    );
  }
}
