import React, { HTMLAttributes } from "react";
import "{2}";
/* 
  Attention: This file is generated by "yarn icon", do not modify 
*/

export enum IconClass {
  // {1}
}


interface Props extends HTMLAttributes<HTMLSpanElement> {
  type: IconClass;
  text?: string;
  textPosition: "left" | "right";
}

export default class Component extends React.PureComponent<Props> {
  public static defaultProps = {
    textPosition: "right"
  };

  render() {
    const { type, text, textPosition, className, ...restProps } = this.props;
    if (text) {
      if (textPosition === "left") {
        return (
          <div
            className={`{3}-with-text-on-left ${className ? className : ""}`}
            {...restProps}
          >
            <span>{text}</span>
            <i className={`{3} ${type}`} {...restProps} />
          </div>
        );
      } else {
        return (
          <div
            className={`{3}-with-text-on-right ${className ? className : ""}`}
            {...restProps}
          >
            <i className={`{3} ${type}`} {...restProps} />
            <span>{text}</span>
          </div>
        );
      }
    } else {
      return (
        <i
          className={`{3} ${type} ${className ? className : ""}`}
          {...restProps}
        />
      );
    }
  }
}
