import React, { AllHTMLAttributes } from "react";
import "{2}";
/* 
  Attention: This file is generated by "yarn icon", do not modify 
*/

export enum IconClass {
  // {1}
}


interface Props extends AllHTMLAttributes<HTMLElement> {
  type: IconClass;
}

export default class Component extends React.PureComponent<Props> {
  render() {
    const { type, className = "", ...restProps } = this.props;
    return <i className={`{3} ${type} ${className}`} {...restProps} />;
  }
}
